name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # 服务器私钥
  SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
  USER_NAME: ${{ secrets.USER_NAME }} # 服务器用户名
  cache-name: note

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: update project
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: ${{ env.SERVER_HOST }}
        user: ${{ env.USER_NAME }}
        private_key: ${{ env.SSH_PRIVATE_KEY }}
        command: cd ~/stock-backend && git pull && /bin/bash server.sh
          
